Repository centre-for-educational-technology/evkk, pull requests merged in 2022-10, with the labels that each got.

#114 New sorting
  ui/src/views/tools/wordanalyser/GrammaticalAnalysis.js
  ui/src/views/tools/wordanalyser/LemmaView.js
  ui/src/views/tools/wordanalyser/Syllables.js
  ui/src/views/tools/wordanalyser/styles/GrammaticalAnalysis.css
  ui/src/views/tools/wordanalyser/styles/LemmaView.css
  ui/src/views/tools/wordanalyser/styles/Syllables.css
Labels: enhancement

#107 Tõlkefunktsionaalsus sõnaanalüsaatorile
  api/src/main/java/ee/tlu/evkk/api/controller/TextController.java
  api/src/main/java/ee/tlu/evkk/api/controller/dto/WordFeatsRequestEntity.java
  core/src/main/java/ee/tlu/evkk/core/service/TextService.java
  core/src/main/java/ee/tlu/evkk/core/service/maps/TranslationMappings.java
  ui/package.json
  ui/src/Nav.js
  ui/src/index.css
  ui/src/resources/flags/eng.png
  ui/src/resources/flags/est.png
  ui/src/translations/en/translations.js
  ui/src/translations/et/translations.js
  ui/src/translations/i18n.js
  ui/src/views/tools/wordanalyser/GrammaticalAnalysis.js
  ui/src/views/tools/wordanalyser/LemmaView.js
  ui/src/views/tools/wordanalyser/Syllables.js
  ui/src/views/tools/wordanalyser/TablePagination.js
  ui/src/views/tools/wordanalyser/WordAnalyser.js
  ui/src/views/tools/wordanalyser/WordInfo.js
  ui/src/views/tools/wordanalyser/textinput/Input.js
  ui/src/views/tools/wordanalyser/textupload/TextUpload.js
  ui/yarn.lock
Labels: enhancement

#115 Added download component to all tables
  ui/package.json
  ui/src/translations/en/translations.js
  ui/src/translations/et/translations.js
  ui/src/views/tools/wordanalyser/DownloadButton.js
  ui/src/views/tools/wordanalyser/GrammaticalAnalysis.js
  ui/src/views/tools/wordanalyser/LemmaView.js
  ui/src/views/tools/wordanalyser/Syllables.js
  ui/src/views/tools/wordanalyser/TablePagination.js
  ui/src/views/tools/wordanalyser/styles/DownloadButton.css
  ui/src/views/tools/wordanalyser/styles/GrammaticalAnalysis.css
  ui/src/views/tools/wordanalyser/styles/LemmaView.css
  ui/src/views/tools/wordanalyser/styles/Syllables.css
  ui/src/views/tools/wordanalyser/styles/TablePagination.css
  ui/src/views/tools/wordanalyser/styles/TextUpload.css
  ui/src/views/tools/wordanalyser/styles/WordAnalyser.css
  ui/src/views/tools/wordanalyser/textinput/Input.js
  ui/src/views/tools/wordanalyser/textinput/InputText.js
  ui/src/views/tools/wordanalyser/textupload/TextUpload.js
  ui/src/views/tools/wordanalyser/textupload/TextUploadModal.js
  ui/yarn.lock
Labels: enhancement

#113 Liitsõnade silbitamise parendamine, sõnaanalüsaatori töö kiirendamine, silbitaja vea parandamine
  stanza-server/server.py
  ui/src/views/tools/wordanalyser/WordAnalyser.js
  ui/src/views/tools/wordanalyser/textinput/Input.js
  ui/yarn.lock
Labels: bugfix

#117 Tühjade sõnaliikide ja vormide korrastamine sõnaanalüsaatoris
  core/src/main/java/ee/tlu/evkk/core/service/TextService.java
  core/src/main/java/ee/tlu/evkk/core/service/maps/TranslationMappings.java
  ui/src/views/tools/wordanalyser/GrammaticalAnalysis.js
Labels: bugfix

#118 Fixed table reset issue
  ui/src/views/tools/wordanalyser/GrammaticalAnalysis.js
  ui/src/views/tools/wordanalyser/LemmaView.js
  ui/src/views/tools/wordanalyser/Syllables.js
  ui/src/views/tools/wordanalyser/WordAnalyser.js
  ui/src/views/tools/wordanalyser/styles/GrammaticalAnalysis.css
Labels: bugfix

#123 Bug/wordanalyser table fix
  ui/src/Routes.js
  ui/src/views/tools/wordanalyser/Contexts/AnalyseContext.js
  ui/src/views/tools/wordanalyser/Contexts/FormContext.js
  ui/src/views/tools/wordanalyser/Contexts/LemmaContext.js
  ui/src/views/tools/wordanalyser/Contexts/SetFormContext.js
  ui/src/views/tools/wordanalyser/Contexts/SetLemmaContext.js
  ui/src/views/tools/wordanalyser/Contexts/SetSyllableContext.js
  ui/src/views/tools/wordanalyser/Contexts/SetTypeContext.js
  ui/src/views/tools/wordanalyser/Contexts/SetWordContext.js
  ui/src/views/tools/wordanalyser/Contexts/SyllableContext.js
  ui/src/views/tools/wordanalyser/Contexts/TabContext.js
  ui/src/views/tools/wordanalyser/Contexts/TypeContext.js
  ui/src/views/tools/wordanalyser/Contexts/WordContext.js
  ui/src/views/tools/wordanalyser/GrammaticalAnalysis.js
  ui/src/views/tools/wordanalyser/LemmaView.js
  ui/src/views/tools/wordanalyser/Syllables.js
  ui/src/views/tools/wordanalyser/TableComponent.js
  ui/src/views/tools/wordanalyser/WordAnalyser.js
  ui/src/views/tools/wordanalyser/WordAnalyserParent.js
  ui/src/views/tools/wordanalyser/textinput/Input.js
  ui/src/views/tools/wordanalyser/textinput/InputText.js
Labels: bug
