Repository centre-for-educational-technology/evkk, pull requests merged in 2024-01, with the labels that each got.

#248 ELLE-277 | implement new syllabification method
  images/evkk-stanza.Dockerfile
  stanza-server/et.dct
  stanza-server/poolita-ja-silbita.sh
  stanza-server/scripts/compile-silbitaja.sh
  stanza-server/scripts/compile-vabamorf.sh
  stanza-server/scripts/evkk-vabamorf.Dockerfile
  stanza-server/scripts/silbita.xfscript
  stanza-server/server.py
  stanza-server/silbitaja.bin
  stanza-server/silbitaja.hfst_olw
  stanza-server/syllabif.ini
  stanza-server/vmeta
  ui/src/elle/tools/wordanalyser/WordAnalyser.js
Labels: enhancement

#254 ELLE-275 | remove "other" selections from query dropdowns, fix displaying of text's "added year" metadata field
  ui/src/elle/const/Constants.js
  ui/src/elle/pages/query/QueryResults.js
Labels: enhancement, bugfix

#255 ELLE-269 | exclude null-lemmas from stanza endpoint outputs, fix creating a deep copy of the wordanalyser's input object
  stanza-server/server.py
  ui/src/elle/tools/wordanalyser/WordAnalyser.js
Labels: bugfix

#257 ELLE-281 | add script for "vanusevahemik" text property based on "vanus", merge two endpoints into one
  api/src/main/java/ee/tlu/evkk/api/controller/TextController.java
  dal/src/main/java/ee/tlu/evkk/dal/dao/TextDao.java
  dal/src/main/java/ee/tlu/evkk/dal/dto/TextAndMetadata.java
  dal/src/main/java/ee/tlu/evkk/dal/dto/TextMetadata.java
  dal/src/main/resources/ee/tlu/evkk/dal/dao/TextDao.xml
  db/src/main/resources/migration/repeatable/R__0008-core.text_property_age_correction.sql
  ui/src/elle/pages/query/QueryResults.js
Labels: bugfix
